//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package br.com.agende.java.util;

import java.util.ArrayList;
import br.com.agende.Appointment;

public class List_Agenda
    extends ArrayList<Appointment>
{


}
