//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package br.com.agende;

import java.util.HashMap;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.GsonHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class Client_
    implements Client
{

    private String rootUrl;
    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;

    public Client_() {
        rootUrl = "http://172.16.143.1:3000";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
    }

    @Override
    public void confirm(String appointment, String token, String status) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("status", status);
        urlVariables.put("token", token);
        urlVariables.put("appointment", appointment);
        try {
            restTemplate.exchange(rootUrl.concat("/confirmations/appointment/{appointment}/{token}?status={status}"), HttpMethod.GET, null, null, urlVariables);
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
            } else {
                throw e;
            }
        }
    }

    @Override
    public Agenda agenda(String patient) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("patient", patient);
        try {
            return restTemplate.exchange(rootUrl.concat("/mobile/agenda/{patient}"), HttpMethod.GET, null, Agenda.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
